"""Hash the phase-6 publication, excluding environments and generated bytecode."""
import argparse
import json
import phase6_edit as study


def run(build):
    target = study.PHASE / 'manifest.json'
    if build:
        if target.exists(): raise FileExistsError(target)
        files = [p for p in study.PHASE.rglob('*') if p.is_file() and p != target
                 and not any(part.startswith('.') or part == '__pycache__' for part in p.relative_to(study.PHASE).parts)]
        files += list((study.ROOT / 'scripts').glob('phase6_*.py'))
        files += [study.ROOT / p for p in ['scripts/test_phase6_edit.py', 'README.md', 'AGENTS.md',
                  'START.md', 'FEASIBILITY.md', 'pyproject.toml', 'uv.lock']]
        study.dump(target, dict(scope='Phase 6 publication; older publication manifests are scoped to their recorded commits',
            freeze_commit='fa9f5e7db94810f017baedec7851785d88e2623f',
            files={str(p.relative_to(study.ROOT)):dict(sha256=study.sha(p),bytes=p.stat().st_size) for p in sorted(set(files))}))
    data = study.load(target)
    for path, item in data['files'].items():
        assert study.sha(study.ROOT / path) == item['sha256'], path
        assert (study.ROOT / path).stat().st_size == item['bytes'], path
    print(json.dumps(dict(verified_files=len(data['files']),bytes=sum(x['bytes'] for x in data['files'].values()))))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(); parser.add_argument('--build', action='store_true')
    run(parser.parse_args().build)
